# These are intended to be changed dynamically
WINDOW_MAX_X = 0
WINDOW_MAX_Y = 0

OUTPUT_HEIGHT = -1
INPUT_HEIGHT = 3
MODAL_HEIGHT = 5

MODAL_BORDER_ENABLED = 1
OUTPUT_BORDER_ENABLED = 1

PREFIX_LEN = 32

DEBUG = False
START_BOT = True
DISABLE_MESSAGE_SEND = True
